global:
  environment: prod
  namespace: prod
  replicaCount: 3
  imagePullPolicy: IfNotPresent
  imagePullSecrets:
    - name: regcred

gateway:
  image:
    repository: gateway-image
    tag: latest
  port: 8000
  servicePort: 30004
  nodeType: NodePort
  envFile: ../gateway/.env
  resources:
    limits:
      cpu: "2"
      memory: "2Gi"

users:
  image:
    repository: users-image
    tag: latest
  port: 8000
  envFile: ../users/.env
  resources:
    limits:
      cpu: "2"
      memory: "2Gi"

orders:
  image: 
    repository: orders-image
    tag: latest
  port: 8000
  envFile: ../orders/.env
  resources:
    limits:
      cpu: "2"
      memory: "2Gi"
